# Generated by Django 4.2.3 on 2023-07-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0003_business_business_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingdataperyear',
            name='business_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendingbusinesses', to='leaf.business'),
        ),
        migrations.CreateModel(
            name='WorkerPayPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(max_length=100)),
                ('average_factory_worker_salary_in_thousands_of_dollars', models.DecimalField(decimal_places=4, max_digits=5)),
                ('average_local_worker_salary_in_thousands_of_dollars', models.DecimalField(decimal_places=4, max_digits=5)),
                ('average_management_salary_in_thousands_of_dollars', models.DecimalField(decimal_places=4, max_digits=5)),
                ('business_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workerpaybusinesses', to='leaf.business')),
            ],
        ),
        migrations.CreateModel(
            name='GHGAssessmentDataPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(max_length=100)),
                ('electricity_from_locations', models.DecimalField(decimal_places=4, max_digits=5)),
                ('electricity_from_factories', models.DecimalField(decimal_places=4, max_digits=5)),
                ('average_employee_commute_in_miles', models.IntegerField()),
                ('employee_count', models.IntegerField()),
                ('average_business_trip_commute_in_miles', models.IntegerField()),
                ('total_business_trips', models.IntegerField()),
                ('total_shipments', models.IntegerField()),
                ('average_shipment_vehicle_type', models.CharField(max_length=100)),
                ('total_miles_shipped', models.IntegerField()),
                ('total_waste_in_pounds', models.CharField(max_length=100)),
                ('main_waste_type', models.CharField(max_length=100)),
                ('total_water_consumption_in_gallons', models.IntegerField()),
                ('pounds_of_plastic_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_cardboard_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_wood_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_paper_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_metal_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_styrofoam_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_tetrapaks_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_glass_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_aluminumfoil_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_petplastic_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_hdpeplastic_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_ldpeplastic_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_palmoil_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_soybeans_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_beef_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_rubber_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pounds_of_cocoa_used', models.DecimalField(decimal_places=4, max_digits=5)),
                ('business_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghgassessmentgbusinesses', to='leaf.business')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingDataPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(max_length=100)),
                ('average_target_age', models.IntegerField()),
                ('percent_women', models.DecimalField(decimal_places=4, max_digits=5)),
                ('target_state', models.CharField(max_length=100)),
                ('business_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalmarketingbusinesses', to='leaf.business')),
            ],
        ),
    ]
