# Generated by Django 4.2.3 on 2023-07-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0004_alter_spendingdataperyear_business_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_industry',
        ),
        migrations.AlterField(
            model_name='ghgassessmentdataperyear',
            name='business_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghgassessmentbusinesses', to='leaf.business'),
        ),
    ]
