# Generated by Django 4.2.3 on 2023-07-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0005_remove_business_business_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingdataperyear',
            name='business_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spendingbusinesses', to='leaf.business'),
        ),
    ]
