# Generated by Django 4.2.3 on 2023-07-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0009_rename_business_id_digitalmarketingdataperyear_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingdataperyear',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendingbusinesses', to='leaf.business'),
        ),
    ]
