# Generated by Django 4.2.3 on 2023-07-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0010_alter_spendingdataperyear_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingdataperyear',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spendingbusinesses', to='leaf.business'),
        ),
    ]
