# Generated by Django 4.2.3 on 2023-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0014_digitalmarketingdataperyear_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalmarketingdataperyear',
            name='average_target_age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalmarketingdataperyear',
            name='percent_women',
            field=models.CharField(max_length=100),
        ),
    ]
