# Generated by Django 4.2.3 on 2023-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0017_remove_ghgassessmentdataperyear_main_waste_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
